@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-start mb-4"><div><a href="{{route('requests.index')}}" class="text-decoration-none"><i class="bi bi-arrow-left"></i> Volver a solicitudes</a><h1 class="page-title h3 mt-3">#{{$serviceRequest->id}} · {{$serviceRequest->title}}</h1><p class="text-secondary mb-0">Creada el {{$serviceRequest->created_at->format('d/m/Y H:i')}} por {{$serviceRequest->student->name}}</p></div><span class="badge badge-status fs-6">{{$serviceRequest->status}}</span></div>
<div class="row g-4"><div class="col-lg-8"><div class="card p-4 mb-4"><div class="d-flex justify-content-between mb-3"><h2 class="h5 fw-bold">Información de la solicitud</h2>@if(!auth()->user()->isAdmin() && $serviceRequest->status==='Pendiente')<div class="d-flex gap-2"><a href="{{route('requests.edit',$serviceRequest)}}" class="btn btn-sm btn-outline-primary"><i class="bi bi-pencil"></i> Editar</a><form method="POST" action="{{route('requests.cancel',$serviceRequest)}}">@csrf<button class="btn btn-sm btn-outline-danger" onclick="return confirm('¿Cancelar esta solicitud?')">Cancelar</button></form></div>@endif</div><div class="row g-3"><div class="col-md-6"><span class="small text-secondary d-block">Categoría</span><strong>{{$serviceRequest->category->name}}</strong></div><div class="col-md-6"><span class="small text-secondary d-block">Ubicación</span><strong>{{$serviceRequest->location}}</strong></div><div class="col-12"><span class="small text-secondary d-block">Descripción</span><p class="mb-0 mt-1" style="white-space:pre-line">{{$serviceRequest->description}}</p></div><div class="col-md-6"><span class="small text-secondary d-block">Prioridad</span><span class="badge {{ $serviceRequest->priority==='Urgente'?'badge-urgent':'badge-priority' }}">{{$serviceRequest->priority}}</span></div><div class="col-md-6"><span class="small text-secondary d-block">Responsable</span><strong>{{$serviceRequest->assignee?->name ?? 'Sin asignar'}}</strong></div></div></div>
<div class="card p-4 mb-4"><h2 class="h5 fw-bold mb-3"><i class="bi bi-paperclip me-2 text-primary"></i>Evidencias</h2>@forelse($serviceRequest->attachments as $attachment)<div class="d-flex justify-content-between align-items-center border-bottom py-2"><span><i class="bi bi-file-earmark me-2"></i>{{$attachment->original_name}} <small class="text-secondary">({{number_format(($attachment->size??0)/1024,0)}} KB)</small></span><a class="btn btn-sm btn-outline-secondary" href="{{route('attachments.download',$attachment)}}">Descargar</a></div>@empty<p class="text-secondary mb-0">No hay evidencias adjuntas.</p>@endforelse
@if(!auth()->user()->isAdmin() || $serviceRequest->status!=='Cancelada')<form method="POST" action="{{route('requests.attachments',$serviceRequest)}}" enctype="multipart/form-data" class="mt-3 d-flex gap-2">@csrf<input class="form-control" type="file" name="evidence" required accept=".jpg,.jpeg,.png,.pdf,.doc,.docx"><button class="btn btn-outline-primary">Adjuntar</button></form>@endif</div>
<div class="card p-4"><h2 class="h5 fw-bold mb-4">Historial cronológico</h2><div class="timeline">@forelse($serviceRequest->histories as $history)<div class="timeline-item"><div class="d-flex justify-content-between"><strong>{{$history->action}}</strong><small class="text-secondary">{{$history->created_at->format('d/m/Y H:i')}}</small></div><div>{{$history->description}}</div><small class="text-secondary">Por {{$history->user?->name ?? 'Sistema'}}</small></div>@empty<p class="text-secondary">Sin movimientos registrados.</p>@endforelse</div></div></div>
<div class="col-lg-4">@if(auth()->user()->isAdmin())<div class="card p-4 mb-4"><h2 class="h5 fw-bold mb-3">Gestionar solicitud</h2><form method="POST" action="{{route('admin.requests.update',$serviceRequest)}}">@csrf @method('PUT')<label class="form-label">Responsable</label><select name="assigned_to" class="form-select mb-3"><option value="">Sin asignar</option>@foreach(\App\Models\User::where('role','administrativo')->orderBy('name')->get() as $admin)<option value="{{$admin->id}}" @selected($serviceRequest->assigned_to===$admin->id)>{{$admin->name}}</option>@endforeach</select><label class="form-label">Estado</label><select name="status" class="form-select mb-3">@foreach(['Pendiente','Asignada','En proceso','Resuelta','Cerrada','Cancelada'] as $status)<option @selected($serviceRequest->status===$status)>{{$status}}</option>@endforeach</select><label class="form-label">Prioridad</label><select name="priority" class="form-select mb-3">@foreach(['Baja','Media','Alta','Urgente'] as $priority)<option @selected($serviceRequest->priority===$priority)>{{$priority}}</option>@endforeach</select><button class="btn btn-primary w-100">Guardar gestión</button></form></div>@endif
<div class="card p-4"><h2 class="h5 fw-bold mb-3">Comentarios</h2>@forelse($serviceRequest->comments as $comment)<div class="border-bottom py-2"><div class="small fw-semibold">{{$comment->user->name}} <span class="text-secondary fw-normal">· {{$comment->created_at->format('d/m/Y H:i')}}</span></div><div class="mt-1" style="white-space:pre-line">{{$comment->body}}</div></div>@empty<p class="text-secondary">Aún no hay comentarios.</p>@endforelse
@if(auth()->user()->isAdmin())<form method="POST" action="{{route('admin.requests.comments',$serviceRequest)}}" class="mt-3">@csrf<textarea name="body" class="form-control mb-2" rows="3" placeholder="Escribe una actualización..." required></textarea><button class="btn btn-outline-primary w-100">Registrar comentario</button></form>@endif</div></div></div>
@endsection
